VERZIJA=CDX
MODUL=fa_1dok
MMODUL=fakt

SRCDOSROOT=$(BASEDOS)\\fmk\\fakt\\dok\\1g\\

PRGS=knjiz.prg stdatn.prg stdok.prg stdok13.prg stdok2.prg stdok23.prg stdok29.prg stdok295.prg stdok2a.prg stdok3.prg stdok30.prg stdokm.prg stdrtf1.prg stdrtf2.prg stdrtf21.prg stdrtf3.prg vknjiz.prg vknjiz2.prg rpt_nar.prg rpt_olpp.prg mnu_dok.prg stdokpdv.prg stdok2p.prg
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
