VERZIJA=CDX
MODUL=fa_1svi
MMODUL=fakt

SRCDOSROOT=c:\\dev\\fmk\\$(MMODUL)\\specif\\vindija\\1g\\

PRGS=distrib.prg vindija.prg mnu_sif.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
