VERZIJA=CDX
MODUL=fa_1srg
MMODUL=fakt


SRCDOSROOT=c:\\dev\\fmk\\$(MMODUL)\\specif\\ramag\\1g\\

PRGS=rn_sdim.prg rn_db.prg tc_rn.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper


