VERZIJA=CDX
MODUL=fa_2dok
MMODUL=fakt

SRCDOSROOT=c:\\dev\\fmk\\$(MMODUL)\\dok\\2g\\

PRGS=frm_inv.prg frm_init.prg rpt_inv.prg rpt_invp.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
