VERZIJA=CDX
MODUL=fa_2dok
MMODUL=fakt

SRCDOSROOT=$(BASEDOS)\\fmk\\fakt\\dok\\2g\\

PRGS=frm_inv.prg frm_init.prg rpt_inv.prg rpt_invp.prg
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
