VERZIJA=CDX
MODUL=fa_1rpt
MMODUL=fakt

SRCDOSROOT=c:\\dev\\fmk\\$(MMODUL)\\rpt\\1g\\

PRGS=izvj.prg rpt_lag.prg rpt_lag2.prg rpt_kart.prg mnu_izvj.prg rpt_nar.prg 
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
