VERZIJA=CDX
MODUL=fa_1rpt

SRCDOSROOT=$(BASEDOS)\\fmk\\fakt\\rpt\\1g\\

PRGS=izvj.prg rpt_lag.prg rpt_lag2.prg rpt_kart.prg mnu_izvj.prg rpt_nar.prg rpt_spr.prg rpt_exp.prg rpt_kol.prg 
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
