VERZIJA=CDX
MODUL=fa_1rdb
MMODUL=fakt

SRCDOSROOT=c:\\dev\\fmk\\$(MMODUL)\\razdb\\1g\\

PRGS=kafak.prg topsfakt.prg mnu_raz.prg rpt_kafa.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

