VERZIJA=CDX
MODUL=fa_1ugo
MMODUL=fakt


SRCDOSROOT=c:\\dev\\fmk\\$(MMODUL)\\ugov\\1g\\

PRGS=genug.prg p_ugov.prg mnu_ugov.prg  
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
